### ISSUE TITLE
Got error when install selinonlib

### ISSUE THREAD

**Issue by yunfeizu** [selinon/demo#7]
Hi,

I'm trying the demo for selinon. 

When running ` docker-compose up`, I got an installation error as below:
```
Complete!
Failed to set locale, defaulting to C
+ pip3 install -U git+https://github.com/selinon/selinonlib
Collecting git+https://github.com/selinon/selinonlib
  Cloning https://github.com/selinon/selinonlib to /tmp/pip-_oj4vatv-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_oj4vatv-build/setup.py", line 31, in <module>
        raise NotImplementedError("This package no longer exists, it was merged with selinon")
    NotImplementedError: This package no longer exists, it was merged with selinon
```
When running ` ./simulate_run.sh`, I got error as below:

```
 SELINON_YAML_FILES_DIR=../worker/myapp/config
+ which which
/usr/bin/which
+ which selinonlib-cli
+ echo 'selinonlib-cli not found, please install it using install_selinon.sh script'
selinonlib-cli not found, please install it using install_selinon.sh script
+ exit 1
```

Am I doing something wrong， or the selinonlib was deprecated? Would you please update your demo code?

**Comment by fridex** [comment]
> Am I doing something wrong， or the selinonlib was deprecated?

Yes, selinonlib was deprecated - merged with selinon as stated in the error message.

> Would you please update your demo code?

Sure, the demo was updated in #8. Please let me know if the issue persists or when you encounter some another issue. Thanks for the report!

**Comment by yunfeizu** [comment]
Thanks for the quick fix. The docker images are running now.
But I got some errors when starting selinon-server and worker. Please refer to below error messages.
```
selinon-server     | Failed to add operation for POST /api/v1/run-flow
selinon-server     | Traceback (most recent call last):
selinon-server     |   File "/usr/lib/python3.5/site-packages/connexion/apis/abstract.py", line 242, in add_paths
selinon-server     |     self.add_operation(method, path, endpoint, path_parameters)
selinon-server     |   File "/usr/lib/python3.5/site-packages/connexion/apis/abstract.py", line 195, in add_operation
selinon-server     |     pythonic_params=self.pythonic_params)
selinon-server     |   File "/usr/lib/python3.5/site-packages/connexion/operation.py", line 215, in __init__
selinon-server     |     resolution = resolver.resolve(self)
selinon-server     |   File "/usr/lib/python3.5/site-packages/connexion/resolver.py", line 40, in resolve
selinon-server     |     return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
selinon-server     |   File "/usr/lib/python3.5/site-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
selinon-server     |     raise ResolverError(msg, sys.exc_info())
selinon-server     | connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "selinon_api.api_v1.post_run_flow"! Import error was "cannot import name 'run_flow'"
```

```
worker_1           | Traceback (most recent call last):
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/app/utils.py", line 355, in find_app
worker_1           |     sym = symbol_by_name(app, imp=imp)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/base.py", line 506, in symbol_by_name
worker_1           |     return imports.symbol_by_name(name, imp=imp)
worker_1           |   File "/usr/lib/python3.5/site-packages/kombu/utils/imports.py", line 61, in symbol_by_name
worker_1           |     return getattr(module, cls_name) if cls_name else module
worker_1           | AttributeError: module 'myapp' has no attribute 'entrypoint'
worker_1           | 
worker_1           | During handling of the above exception, another exception occurred:
worker_1           | 
worker_1           | Traceback (most recent call last):
worker_1           |   File "/usr/bin/celery", line 11, in <module>
worker_1           |     sys.exit(main())
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/__main__.py", line 14, in main
worker_1           |     _main()
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/celery.py", line 326, in main
worker_1           |     cmd.execute_from_commandline(argv)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
worker_1           |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
worker_1           |     argv = self.setup_app_from_commandline(argv)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
worker_1           |     self.app = self.find_app(app)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/bin/base.py", line 503, in find_app
worker_1           |     return find_app(app, symbol_by_name=self.symbol_by_name)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/app/utils.py", line 358, in find_app
worker_1           |     sym = imp(app)
worker_1           |   File "/usr/lib/python3.5/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
worker_1           |     return imp(module, package=package)
worker_1           |   File "/usr/lib64/python3.5/importlib/__init__.py", line 126, in import_module
worker_1           |     return _bootstrap._gcd_import(name[level:], package, level)
worker_1           |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
worker_1           |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
worker_1           |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
worker_1           |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
worker_1           |   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
worker_1           |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
worker_1           |   File "/usr/lib/python3.5/site-packages/myapp/entrypoint.py", line 8, in <module>
worker_1           |     from .configuration import init
worker_1           |   File "/usr/lib/python3.5/site-packages/myapp/configuration.py", line 10, in <module>
worker_1           |     from selinon import Config
worker_1           | ImportError: cannot import name 'Config'
demo_worker_1 exited with code 1
```

**Comment by fridex** [comment]
> But I got some errors when starting selinon-server and worker.

I'm unable to reproduce this. Try to rebuild without cache:

```
docker-compose build --no-cache
```

**Comment by fridex** [comment]
Just wondering what could be an issue here. Probably there's mounted an empty directory with selinon sources if you did not initialized also selinon submodule.

I've pushed 05fdfbffabf1686d5d31fc07df4293339184d2b2 so it should be ok running without submodules by default.

**Comment by yunfeizu** [comment]
The demo is up running. Thanks!
